import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ProgramType, ProgressStartType } from "@prisma/client";
import { formatDate, getSurahName } from "@/lib/utils";
import { progressSummaryLabel } from "@/lib/student-progress";

export type ReportType = "attendance" | "hifz" | "combined";

export type StudentReportData = {
  instituteName: string;
  student: {
    fullName: string;
    studentId: string;
    programType: ProgramType;
    progressStartType: ProgressStartType | null;
    previousInstitute: string | null;
    currentJuz: number | null;
    currentPara: number | null;
    currentSurah: number | null;
    currentPage: number | null;
    teacherName: string;
    parentName: string;
    parentEmail: string | null;
  };
  period: { from: string; to: string };
  attendance: {
    rows: Array<{ date: string; status: string }>;
    present: number;
    absent: number;
    late: number;
    leave: number;
    rate: number;
  };
  hifz: {
    rows: Array<{
      date: string;
      type: string;
      surah: string;
      ayahs: string;
      rating: number;
      errors: number;
    }>;
    avgRating: number;
  };
  generatedBy: string;
  generatedAt: Date;
};

function addHeader(doc: jsPDF, title: string, data: StudentReportData) {
  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("QEMS — Student Progress Report", 14, 12);
  doc.setFontSize(10);
  doc.text(data.instituteName, 14, 19);
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(14);
  doc.text(title, 14, 38);
  doc.setFontSize(10);
  doc.text(`${data.student.fullName} (${data.student.studentId})`, 14, 46);
  doc.text(`Program: ${data.student.programType} · Period: ${formatDate(data.period.from)} – ${formatDate(data.period.to)}`, 14, 52);
}

function addStudentInfo(doc: jsPDF, data: StudentReportData, startY: number) {
  autoTable(doc, {
    startY,
    head: [["Field", "Value"]],
    body: [
      ["Student", data.student.fullName],
      ["Student ID", data.student.studentId],
      ["Program", data.student.programType],
      ["Progress", progressSummaryLabel(data.student.programType, data.student)],
      ["Teacher", data.student.teacherName],
      ["Parent / Guardian", data.student.parentName],
      ["Parent Email", data.student.parentEmail || "—"],
    ],
    theme: "grid",
    headStyles: { fillColor: [22, 101, 52] },
    styles: { fontSize: 9 },
    margin: { left: 14, right: 14 },
  });
}

function addAttendanceSection(doc: jsPDF, data: StudentReportData, startY: number) {
  doc.setFontSize(12);
  doc.setTextColor(22, 101, 52);
  doc.text("Attendance Summary", 14, startY);
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(
    `Present: ${data.attendance.present} · Absent: ${data.attendance.absent} · Late: ${data.attendance.late} · Leave: ${data.attendance.leave} · Rate: ${data.attendance.rate}%`,
    14,
    startY + 6
  );

  autoTable(doc, {
    startY: startY + 10,
    head: [["Date", "Status"]],
    body: data.attendance.rows.length
      ? data.attendance.rows.map((r) => [formatDate(r.date), r.status])
      : [["—", "No attendance records in this period"]],
    theme: "striped",
    headStyles: { fillColor: [22, 101, 52] },
    styles: { fontSize: 8 },
    margin: { left: 14, right: 14 },
  });
}

function addHifzSection(doc: jsPDF, data: StudentReportData, startY: number) {
  doc.setFontSize(12);
  doc.setTextColor(22, 101, 52);
  doc.text("Hifz / Quran Learning Activity", 14, startY);
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(`Average lesson rating: ${data.hifz.avgRating ? data.hifz.avgRating.toFixed(1) : "—"} / 5`, 14, startY + 6);

  autoTable(doc, {
    startY: startY + 10,
    head: [["Date", "Type", "Surah", "Ayahs", "Rating", "Errors"]],
    body: data.hifz.rows.length
      ? data.hifz.rows.map((r) => [formatDate(r.date), r.type, r.surah, r.ayahs, String(r.rating), String(r.errors)])
      : [["—", "—", "No hifz records in this period", "—", "—", "—"]],
    theme: "striped",
    headStyles: { fillColor: [22, 101, 52] },
    styles: { fontSize: 8 },
    margin: { left: 14, right: 14 },
  });
}

function addFooter(doc: jsPDF, data: StudentReportData) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by ${data.generatedBy} on ${data.generatedAt.toLocaleString("en-PK")} · Page ${i} of ${pageCount}`,
      14,
      290
    );
    doc.text("Confidential — For parent/guardian use", 14, 295);
  }
}

export function buildStudentReportPdf(type: ReportType, data: StudentReportData): Uint8Array {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const titles: Record<ReportType, string> = {
    attendance: "Attendance Report",
    hifz: "Hifz Progress Report",
    combined: "Combined Student Report",
  };

  addHeader(doc, titles[type], data);
  let y = 58;

  if (type === "combined") {
    addStudentInfo(doc, data, y);
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  }

  if (type === "attendance" || type === "combined") {
    addAttendanceSection(doc, data, y);
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
    if (type === "combined" && y > 240) {
      doc.addPage();
      y = 20;
    }
  }

  if (type === "hifz" || type === "combined") {
    if (type === "hifz") {
      addStudentInfo(doc, data, y);
      y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
    }
    if (data.student.programType === ProgramType.HIFZ) {
      addHifzSection(doc, data, y);
    } else {
      doc.setFontSize(10);
      doc.text("Hifz records apply to Hifz program students only.", 14, y);
    }
  }

  addFooter(doc, data);
  return doc.output("arraybuffer") as unknown as Uint8Array;
}

export function programTypeLabel(type: ProgramType) {
  if (type === ProgramType.NAZRA) return "Nazra";
  if (type === ProgramType.TAJWEED) return "Tajweed";
  return "Hifz";
}

export { getSurahName };
